'use client';

import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X,
  Printer,
  Download,
  FileText,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  Building2,
  Calendar,
} from 'lucide-react';
import { AIAnalysisOutput } from '@/services/aiCopilotService';

export function ExecutiveReportModal({
  isOpen,
  onClose,
  analysis,
}: {
  isOpen: boolean;
  onClose: () => void;
  analysis?: AIAnalysisOutput;
}) {
  if (!isOpen || !analysis) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-slate-950/80 backdrop-blur-md overflow-y-auto">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 10 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 10 }}
          className="relative w-full max-w-4xl max-h-[90vh] flex flex-col rounded-3xl border border-slate-700 bg-slate-900 shadow-2xl overflow-hidden text-slate-100"
        >
          {/* Modal Header */}
          <div className="flex items-center justify-between p-6 border-b border-slate-800 bg-slate-950">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-blue-600/20 text-blue-400 border border-blue-500/30">
                <FileText className="h-5 w-5" />
              </div>
              <div>
                <h3 className="text-base font-extrabold text-white">
                  WarehouseIQ Executive Operations Report
                </h3>
                <span className="text-xs text-slate-400">
                  Facility: Hub Central-01 (NA-EAST-1) • Shift: Morning
                </span>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={handlePrint}
                className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold rounded-xl shadow-md transition-colors"
              >
                <Printer className="h-3.5 w-3.5" />
                <span>Print / Save PDF</span>
              </button>
              <button
                type="button"
                onClick={onClose}
                className="p-2 text-slate-400 hover:text-white rounded-xl hover:bg-slate-800 transition-colors"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          </div>

          {/* Printable Report Body */}
          <div className="flex-1 overflow-y-auto p-8 space-y-6 text-xs text-slate-200">
            {/* Title & Metadata */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-800">
              <div>
                <span className="text-[10px] font-bold uppercase tracking-widest text-blue-400 block mb-1">
                  Confidential Operations Briefing
                </span>
                <h1 className="text-xl font-extrabold text-white">
                  Daily Facility Health &amp; Decision Intelligence Audit
                </h1>
                <p className="text-xs text-slate-400 mt-1">
                  Generated by Autonomous Operations Director Engine
                </p>
              </div>

              <div className="text-left sm:text-right space-y-1 text-xs">
                <p><b className="text-slate-400">Date:</b> {new Date().toLocaleDateString()}</p>
                <p><b className="text-slate-400">Overall Health Score:</b> <span className="text-emerald-400 font-bold font-mono">{analysis.warehouseHealth.score}%</span></p>
                <p><b className="text-slate-400">Risk Level:</b> <span className="text-amber-400 font-bold">{analysis.riskLevel}</span></p>
              </div>
            </div>

            {/* Executive Summary */}
            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
                1. Executive Strategic Summary
              </h4>
              <p className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-200 leading-relaxed">
                {analysis.executiveSummary}
              </p>
            </div>

            {/* Critical Operational Exceptions */}
            <div className="space-y-3">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
                2. High-Severity Operational Exceptions
              </h4>
              <div className="space-y-2">
                {analysis.criticalIssues.map((issue) => (
                  <div
                    key={issue.id}
                    className="p-3 rounded-lg bg-slate-950 border border-slate-800 flex items-start justify-between gap-4"
                  >
                    <div className="space-y-0.5">
                      <span className="font-bold text-white text-xs">{issue.title}</span>
                      <p className="text-[11px] text-slate-400">{issue.description}</p>
                    </div>
                    <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded bg-rose-500/20 text-rose-300 border border-rose-500/30 shrink-0">
                      {issue.severity}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Strategic Recommendations */}
            <div className="space-y-3">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
                3. Operations Director Directives &amp; Prescriptions
              </h4>
              <div className="space-y-2">
                {analysis.recommendations.map((rec) => (
                  <div
                    key={rec.id}
                    className="p-3.5 rounded-lg bg-slate-950 border border-slate-800 space-y-1"
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-blue-300 text-xs">{rec.title}</span>
                      <span className="text-[10px] font-mono text-emerald-400 font-bold">{rec.confidence}% Confidence</span>
                    </div>
                    <p className="text-xs text-slate-300"><b>Action:</b> {rec.action}</p>
                    <p className="text-[11px] text-slate-400"><b>Expected Benefit:</b> {rec.impact}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Signoff */}
            <div className="pt-6 border-t border-slate-800 flex items-center justify-between text-[11px] text-slate-500 font-mono">
              <span>WarehouseIQ Decision Intelligence Core v2.0</span>
              <span>Signed: Operations Director (Autonomous AI Agent)</span>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
